#!/usr/bin/env python

#
# Copyright 2007 !j Incorporated
#
# This file is part of Canner.
#
# Canner is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canner is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Canner.  If not, see <http://www.gnu.org/licenses/>.
#

# $Id: rwhois-lookup 13 2008-01-29 16:19:21Z keith $

from __future__ import with_statement
import os, re, sys, socket
from itertools import count, izip
from collections import defaultdict
from canner import taglib
import IPy


def rwhois_query(query):
    queue = [("rwhois.arin.net", 4321)]
    result = ""

    while queue:
        host, port = queue.pop()

        s = None
        for res in socket.getaddrinfo(host, port, socket.AF_UNSPEC,
                                      socket.SOCK_STREAM):
            af, socktype, proto, canonname, sa = res
            try:
                s = socket.socket(af, socktype, proto)
            except socket.error:
                s = None
                continue
            try:
                s.connect(sa)
            except socket.error:
                s.close()
                s = None
                continue
            break
        if s is None:
            print "# could not connect to rwhois server '%s'" % host
            continue

        s.send(query + "\n")
        res = ""
        while True:
            data = s.recv(4096)
            if not data: break
            res += data
        s.close()
        result += res

        for m in re.finditer(r"(?m)^%referral rwhois://(.*?):(\d+)/", res):
            queue.append(m.groups())

    return result


def extract_tags(context, src, filename):
    def ot(line, qname, properties=None, **kw):
        taglib.output_tag(filename, line, qname, properties, **kw)

    m = re.match(r"IPv4 subnet--(.*)/\d+", context)
    subnet_ip = IPy.IP(m.group(1))
    
    attrs = defaultdict(list)
    in_context = False
    for linenum, line in src:
        line = line.strip()

        if line.startswith("#TAG: "):
            if in_context:
                return True
            if line == "#TAG: " + context:
                in_context = True

        if not in_context:
            continue

        if line == "":
            if not attrs:
                continue

            reg_net_tag = None
            for ln, val in attrs["IP-Network"]:
                registered_ip = IPy.IP(val)
                if subnet_ip in registered_ip:
                    reg_net_tag = "registered network subnet--" + val
                    reg_net_props = taglib.ip_subnet(val)[1]
                    break

            if not reg_net_tag:
                print "# could not find IP-Network for %s" % subnet_ip
            else:
                ot(ln, reg_net_tag, reg_net_props, context=context)
                
                ln, val = attrs["ID"][0]
                id_tag = "registered network--" + val
                ot(ln, id_tag, context=reg_net_tag)

                org_names = attrs["Org-Name"] or attrs["Organization"]
                if org_names:
                    ln, val = org_names[0]
                    ot(ln, "registered organization--" + val,
                     context=reg_net_tag)

            attrs = defaultdict(list)

        elif line.startswith("#"):
            pass

        elif line.startswith("%"):
            pass

        else:
            m = re.match(r"^network:(.*?)(;.)?:(.*?)$", line)
            if not m:
                print "# unexpected line: %r" % line
            else:
                name, valtype, value = m.groups()
                attrs[name].append((linenum, value))

    return in_context


def main():
    tag = os.environ["TAG"]

    m = re.match(r"IPv4 subnet--(.*)/\d+", tag)
    if not m:
        print >>sys.stderr, "could not get subnet from tag"
        sys.exit(1)
    subnet = m.group(1)

    filename = "rwhois.log"
    line_counter = count(1)

    found = False
    if os.path.exists(filename):
        with open(filename) as f:
            found = extract_tags(tag, izip(line_counter, f), filename)
    if not found:
        print "# result not found -- querying rwhois"
        result = "#TAG: " + tag + "\n" + rwhois_query("IP-Network=%s" % subnet)
        with open(filename, "a") as f:
            f.write(result)
        line_counter = count(line_counter.next() - 1)
        extract_tags(tag, izip(line_counter, result.splitlines()), filename)
        taglib.output_tag(filename, 0, "file--" + filename)


if __name__ == "__main__":
    main()
