#!/usr/bin/env python

#
# Copyright 2007 !j Incorporated
#
# This file is part of Canner.
#
# Canner is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canner is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Canner.  If not, see <http://www.gnu.org/licenses/>.
#

import os, sys
from datetime import datetime
from canner import taglib

device    = os.environ["SESSION_DEVICE"]
sid       = os.environ["SESSION_ID"]
os_name   = os.environ["SESSION_OS_NAME"]
timestamp = os.environ["SESSION_TIMESTAMP"]
user      = os.environ["SESSION_USER"]

format_ts = datetime.strptime(timestamp, "%Y-%m-%dT%H:%M:%S").strftime
ts = format_ts("%Y-%m-%dT%H:%M:%S")
ts_display = format_ts("%Y-%m-%d %H:%M")

sess_tag = taglib.tag("snapshot", sid,
                      sort_name="%s @ %s" % (device, ts),
                      display_name="%s @ %s" % (device, ts_display))
sess_tag.used()
                      
dev_tag = taglib.tag("device", device)
dev_tag.implied_by(sess_tag)

taglib.tag("snapshot user", user).implied_by(sess_tag)
taglib.tag("OS", os_name).implied_by(dev_tag)

t = taglib.tag("snapshot timestamp", ts, display_name=ts_display)
t.implied_by(sess_tag)
t = taglib.tag("snapshot date", format_ts("%Y-%m-%d")).implied_by(t)
t = taglib.tag("snapshot month", format_ts("%Y-%m")).implied_by(t)
t = taglib.tag("snapshot year", format_ts("%Y")).implied_by(t)


taglib.output_tagging_log()
